image: node:latest

e2e_test:
    image: trion/ng-cli-e2e
    cache:
        paths:
          - node_modules/
    before_script:
        - npm install -g @angular/cli
        - npm install
    stage: test
    only:
        - feature/gitlab-cd
    script:
        - npm run e2e

deploy_prod:
    image: andreysenov/firebase-tools
    before_script:
      - npm install -g @angular/cli
      - npm install
    stage: deploy
    environment:
        name: production
    only:
        - feature/gitlab-cd
    script:
        - npm run build-prod
        - npm run deploy-firebase
    artifacts:
        paths:
            - dist/
